# Generated by Django 3.2.6 on 2021-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('symbol', models.CharField(blank=True, max_length=25, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('symbol', models.CharField(blank=True, max_length=25, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
