# Generated by Django 3.2.6 on 2021-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_scrapenews_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapenews',
            name='pubDate',
            field=models.DateTimeField(),
        ),
    ]
